-----
### 에러 핸들링 (Error Handling)의 필요성
-----
: 에러(Error) 발생에 대비하지 않으면, 프로그램이 종료

```js
console.log('에러 발생 전');

// ⚠️ 오류를 발생시키는 코드
(3).split(''); // 숫자 타입의 문자열 메서드 split 함수 적용 

// 출력되지 않음
console.log('에러 발생 후');
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/2cca806d-6573-41a2-8a8f-3035842c6b37">
</div>

-----
### 자바스크립트의 에러 핸들링
-----
: https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/try...catch

1. try ... catch 문
```js
console.log('에러 발생 전');

try {
  (3).split('');

} catch (e) {
  console.error('🛑 에러!!', e);
}

console.log('에러 발생 후');
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/9bfed767-cd39-4b7b-a190-59c98769e179">
</div>

  - try 블록
    + 에러 발생 여지가 있는 코드 포함
    + 이곳에서 발생한 에러는 프로그램을 멈추게 하지 않음

  - catch 블록
    + 에러 발생 시 실행할 코드 포함
    + 발생한 오류 객체를 인자로 받음

```js
const arr = ['ABC', '가나다', 123, '123'];

function getLetterArray (str) {
  // 💡 인자로 어떤 타입의 값이 주어질지 모르는 상황
  try {
    return str.split('');

  } catch (e) {
    console.error('🛑 에러!!', e);
    return [];
  }
}

arr.forEach(i => {
  console.log(getLetterArray(i));
});
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/3b243976-a8b0-459d-ad3a-1e7b78a036a1">
</div>

2. try ... catch ... finally 문
   - fianlly 블록
     + 오류 발생 여부와 관계 없이 한 번 실행되는 코드 포함
```js
function connect () { console.log('☀️', '통신 연결'); }
function disconnect () { console.log('🌙', '통신 연결 해제'); }
function sendArray (arr) { console.log('전송', arr); }

function sendStringAsArray (str) {
  connect();

  try {
    sendArray(str.split(''));
    return true;

  } catch (e) {
    console.error('🛑 에러!!', e);
    return false;

  } finally {
    // 💡 전송 성공 여부와 관계없이 연결은 끊어야 함
    disconnect();
    console.log('- - - - - - - -');
  }

  // ❓ 이곳에 넣는 것과 무엇이 다른가?
  // 아래로 대체하여 실행해 볼 것
  // disconnect();
  // console.log('- - - - - - - -');
}

['ABC', '가나다', 123, '123'].forEach(i => {
  console.log(
    sendStringAsArray(i) 
    ? '[성공]' : '[실패]', '\n\n'
  );
});
```
  - try나 catch문에 return이 있더라도 반드시 fianlly문은 실행
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/3f464326-c8be-4204-b7fc-98c3bf4d6e4e">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/4a581aed-b2f9-4a24-9403-89ffaafd989b">
</div>

  - 주석을 서로 바꿔서 실행하면, return문에 의해 finally 문은 미 실행, 아래 코드 또한 return문에 의해 미실행
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/8d9508ba-581f-4cbd-984e-863ee2ace2f1">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/e3c8f89c-ebe1-4ead-aa46-597529aa2e6d">
</div>

-----
### Error 객체
-----
* 위의 코드에서 console.log(e)와 e에 대한 typeof를 확인하면, object와 이에 맞는 내용이 string으로 출력됨을 알 수 있음
  - 즉, error를 담고 있는 것 또한 객체
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/eb8173b0-0015-439a-8491-c4dd109fcc12">
</div>

: https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error
1. 에러 발생 시 던져지는(thrown) 객체
2. 에러에 대한 정보를 담고 있음
3. 에러가 발생하지 않아도, 직접 생성하여 던지기 가능
4. 기본 생성과 사용법
  - 기본 생성 : new Error('Message');
```js
const error = new Error('뭔가 잘못됐어');

console.error(error);
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/1779aace-f9f0-44aa-bf4d-05ade5d209fa">
</div>

  - 두 번째 인자로 객체를 통해 이유 명시 가능
```js
// 두 번째 인자로 이유를 명시할 수도 있음
const error = new Error(
  '뭔가 잘못됐어',
  { cause: '뭘 잘못했으니까' }
);

console.error(error);
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/c6c34656-59c6-44da-ac06-8746a5fb00f2">
</div>

  - 기본 인스턴스 프로퍼티와 메서드
```js
console.log(error.name);
console.log(error.message);

// cause를 입력했을 경우
console.log(error.cause);

// 에러 자체를 로그 출력하면 나오는 문구
console.log(error.toString());
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/04757416-cd50-45ec-a468-0f6af4f49902">
</div>

5. 의도적으로 에러 발생시키는 방법
```js
throw new Error('이유를 묻지 마라');
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/c87f3882-20f9-4259-a6a2-598461961576">
</div>

-----
### Error의 종류
-----
1. 아래 에러는 모두 Error Class로부터 상속 받음
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/e3a64a84-e8af-4c37-8640-f9210758a56f">
</div>

   - 어떤 문제에 의한 에러인지 쉽게 식별 가능
   - 기타 에러 유형 : https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error#%EC%98%A4%EB%A5%98_%EC%9C%A0%ED%98%95

2. 예제
   - SyntaxError
```js
const x x;
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/c29477af-734a-4b06-b872-d1f653d816d2">
</div>

```js
const errorFuncs = [
  // 자료형에 맞지 않는 메서드 호출 (TypeError)
  () => { (3).split(''); },

  // 선언되지 않은 함수 호출 (ReferenceError)
  () => { hello(); },

  // 부적절한 숫자를 인자로 전달 (RangeError)
  () => { (123.45).toFixed(-1); }
];

errorFuncs.forEach(func => {
  try {
    func();

  } catch (e) {
    console.error(e);
    console.log(e.name);
    console.log(e.message, '\n\n');
  }
});
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/ec735c13-7a86-4da3-9c60-aacb9cbf9352">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/33e8b10b-a89a-46e0-be6a-90b6b6c8e7cc">
</div>

3. 오류 종류에 따라 대처하기
```js
errorFuncs.forEach(func => {
  try {
    func();

  } catch (e) {
    if (e instanceof TypeError) {
      console.error('자료형 확인하세요.');
      return;
    }
    if (e instanceof ReferenceError) {
      console.error('선언 안 된 거 쓴 거 없는지 확인하세요.');
      return;
    }
    console.error('아니, 뭘 한 거에요?');
  }
});
````
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/52832a17-37ed-4eec-9fd0-56e3ef04d34c">
</div>

4. 직접 오류를 생성하여 던지기
   - 컴퓨터가 인지하지 못하는 에러 수동 발생
```js
// 특정 월의 당번으로 지원하는 함수
function applyForMonth (date) {
  try {
    if (typeof date !== 'number') { // TypeError
      throw new TypeError('숫자로 입력해주세요.');
    }
    if (date < 1 || date > 12) { // RangeError
      throw new RangeError('유효한 월을 입력해주세요.');
    }

    console.log(`${date}월 당번으로 등록되셨습니다.`); // 에러가 없을 시

  } catch (e) {
    console.error('🛑 에러 발생!', e);
    console.log('다시 등록해주세요.');
  }
}

applyForMonth(5);

applyForMonth('5');

applyForMonth(13);
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/e257aaea-d766-4333-a960-35ba10008ec4">
</div>

4. 커스텀 에러 만들기
   : https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error#%EC%82%AC%EC%9A%A9%EC%9E%90_%EC%A0%95%EC%9D%98_%EC%97%90%EB%9F%AC_%ED%83%80%EC%9E%85
   
```js
class MilitaryError extends Error {
  constructor (position, ...params) {
    super(...params); // 부모 클래스인 Error클래스의 인자로 ...params, 즉 스프레드 된 내용이 super로 통해 에러 메세지로 적용

    this.name = 'MilitaryError'; // 해당 에러의 이름

    switch (position) {
      case '이병':
        this.message = '개판이군. 맞선임 데려와봐.'; // super, 즉 Error 클래스의 메세지 (this.message 위에 덮어씌어짐)
        break;
      case '일병':
        this.message += ' 엎드려 뻗쳐.'; // super, 즉 Error 클래스의 메세지 (this.message 뒤에 포함해서 message 출력)
        break;
      case '상병':
        this.message = '짬을 거꾸로 먹었나. ' + this.message; // super, 즉 Error 클래스의 메세지 (해당 메세지 뒤 this.message가 출력)
        break;
      default:
        this.message = '집에 갈 때 됐다 이거지? ㅎㅎ'; // super, 즉 Error 클래스의 메세지 (this.message 위에 덮어씌어짐)
    }
  }
}

class Soldier {
  constructor (position) {
    this.position = position;
  }

  speak (word) {
    console.log(this.position + ':', word);
    try {
      if (!'다나까'.includes(word.at(-1))) {
        throw new MilitaryError(
          this.position,
          '군대에서 모든 말은 다나까로 끝낸다.'
        );
      }

    } catch (e) {
      console.error(e);
    }
  }
}
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/a6a2c388-e441-4dc9-b397-1e93f1dd3472">
</div>

```js
['이병', '일병', '상병', '병장'].forEach(pos => {
  const soldier = new Soldier(pos);
  soldier.speak('무슨 일입니까'); // 다나까로 끝나므로 정상적 실행
  soldier.speak('왜요'); // 다나까로 끝나지 않으므로 MilitrayError 발생
});
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/67aa97dd-953e-4a6e-ab9f-376b887a0b31">
</div>

-----
### Error Bubbling
-----
1. 다른 함수를 호출 했을 때
   - 에러 발생 시 해당 함수에서 잡지 않으면 호출한 곳으로 던져짐
   - 다중 호출 시 에러를 핸들링하는 코드가 있는 호출자까지 전달됨
   - 다음 코드는 func4 - func3 - func2 - func1 순으로 호출되며, func1에서 에러가 발생했으나 처리하지 않았음
   - func1에 의해 에러가 발생했으나 종료되지 않고, 이를 호출한 곳들로 계속 에러가 던져지고, 이를 func4에서 처리
```js
function func1 () {
  throw new Error('에러');
}

function func2 () {
  func1();
}

function func3 () {
  func2();
}

function func4 () {
  try {
    func3();

  } catch (e) {
    console.error(e);
  }
  console.log('실행완료');
}

func4();
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/7482a4b0-5f4b-40c0-b006-098c5669fe3d">
</div>

  - 그러나, 에러는 가능한 발생한 곳 가까이서 처리하는 것이 좋음

```js
function func1 (e) { // 사원
  try {
    if (e) { throw e }
    console.log('저 가 봐도 되죠?');
    console.log('- - - - - - - - - -');

  } catch (e) {
    if (e instanceof SyntaxError) {
      console.error('저 이건 알아요!', e);
      console.log('- - - - - - - - - -');
      return;
    }
    console.log('대리님, 이거 뭐에요?');
    throw e; // 💡 처리하지 못하는 에러는 윗선으로 던짐
  }
}

function func2 (e) { // 대리
  try {
    func1(e);
  } catch (e) {
    if (e instanceof TypeError) {
      console.error('내가 할 테니 가봐요.', e);
      console.log('- - - - - - - - - -');
      return;
    }
    console.log('부장님, 이건 제 선에서 안 되겠습니다.');
    throw e; // TypeError가 아닌 경우
  }
}

function func3 (e) { // 부장
  try {
    func2(e);
  } catch (e) {
    if (e instanceof ReferenceError) {
      console.error('잘 하자, 응?', e);
      console.log('- - - - - - - - - -');
      return;
    }
    console.log('사장님, 이것 좀 보셔야겠습니다.');
    throw e; // ReferenceError가 아닌 경우
  }
}

function func4 (e) { // 사장
  try {
    func3(e);

  } catch (e) {
    console.error('전원 집합.', e);
  }
}
```

```js
func4();

func4(new SyntaxError());

func4(new TypeError());

func4(new ReferenceError);

func4(new RangeError);
```
<div align="center">
<img src="https://github.com/sooyounghan/JavaScript/assets/34672301/382774f1-0112-4704-b57d-6c760a6e6e0d">
</div>
